### ISSUE TITLE
Missing file gridfuncs.pyx.

### ISSUE THREAD

**Issue by AlexeyReshetnyak** [tsoernes/dca#1]
There is the following problem with missing file:
python3 dca/setup.py build
running build
running build_ext
cythoning gridfuncs.pyx to gridfuncs.c
error: [Errno 2] No such file or directory: '/home/al/projects/dca/gridfuncs.pyx'

**Comment by tsoernes** [comment]
Sorry about that. The project does not have a working requirements or `setup.py` file. The `gridfuncs.pyx` requirement is outdated -- cython is not used anywhere in the project.
