### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by tangtangsiqi** [tsoernes/dca#3]
i tried to run the code with the following examples
python3 main.py tftdcsinghnet --hoff_lookahead --erlangs 10 --p_handoff 0.15
but there is segmentation fault
how to solve it or how to train the basic reinforcement learning network to allocation channel?

**Comment by tsoernes** [comment]
do you have a full traceback?

**Comment by tangtangsiqi** [comment]
if i comment 
#import strats.qnet_rl  # noqa
#import strats.table_rl  # noqa
#import strats.vnet_rl  # noqa
in main.py, the debug can move on, however there is still error as the following:

main.py: error: argument strat: invalid choice: 'tftdcsinghnet' (choose from 'show')

is it means the configuration example i use (tftdcsinghnet --hoff_lookahead --erlangs 10 --p_handoff 0.15) is not suitable?

**Comment by tsoernes** [comment]
You get that error because you've commented out `import strats.vnet_rl`, where tftdcsinghnet is defined

**Comment by tangtangsiqi** [comment]
so how to fix it？ 1666455856 邮箱：1666455856@qq.com 签名由 网易邮箱大师 定制 On 12/30/2019 23:40, tsoernes wrote: You get that error because you've commented out import strats.vnet_rl, where tftdcsinghnet is defined — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tangtangsiqi** [comment]
I delete the comment of such lines and tried to figure out the segmentation fault.
however there is still the error "main.py: error: argument strat: invalid choice: 'tftdcsinghnet' (choose from 'show')"
is there other examples of the reinforcement learning?

**Comment by tsoernes** [comment]
I'm sorry I can't help you much. This repo is not really in a runnable state since dependencies are missing. I would guess that a segfault would be caused by either numba or tensorflow.
